meta_name: "LuckyPet"
meta_title: "LuckyPet - Pour un chien bien dans ses pattounes"
meta_description: "Pour un chien bien dans ses pattounes"
meta_image: "meta-image.png" # should exist in `app/assets/images/`
twitter_account: "@BecquesA"   # required for Twitter Cards
